spring:
  profiles:
    active: herokudev
  jpa:
    hibernate:
        ddl-auto: none
        naming:
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        proc:
          param_null_passing: true
        order_inserts: true
        order_updates: true
        session_factory:
            interceptor: com.itsight.interceptor.EntityInterceptorImpl
        jdbc:
            batch_size: 400
            batch_versioned_data: true
    open-in-view: false
  # Templates reloading during development
  thymeleaf:
    cache: false
    encoding: UTF-8
    suffix: .html
    #prefix: file:src/main/resources/templates/
# Static resources reloading during development
  resources:
    #static-locations: file:src/main/resources/static/
  servlet:
    multipart:
      max-request-size: 128MB
      max-file-size: 64MB
# Mail properties
  mail:
    host: smtp.gmail.com
    username: contoso.peru@gmail.com
    password: p1ls3n@147
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
#jmail.properties.mail.smtp.EnableSSL.enable:true;
